version: '2'
services:
  nginx:
    build:
      context: ./
      dockerfile: docker/nginx.docker
    volumes:
      - ./:/var/www
      - ./docker/nginx/ssl:/etc/nginx/ssl
    ports:
      - "8080:443"
    links:
      - php-fpm
  php-fpm:
    build:
      context: ./
      dockerfile: docker/php-fpm.docker
    volumes:
      - ./:/var/www
    links:
      - mysql
      - redis
    environment:
      - "DB_HOST=mysql"
      - "DB_PORT=3306"
      - "REDIS_HOST=redis"
      - "REDIS_PORT=6379"
  php-cli:
    build:
      context: ./
      dockerfile: docker/php-cli.docker
    volumes:
      - ./:/var/www
    links:
      - mysql
      - redis
    environment:
      - "DB_PORT=3306"
      - "DB_HOST=mysql"
      - "REDIS_PORT=6379"
      - "REDIS_HOST=redis"
    tty: true
  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password --sql_mode="NO_UNSIGNED_SUBTRACTION"
    volumes:
      - $PWD/storage/docker/mysql:/var/lib/mysql
    environment:
      - "MYSQL_ROOT_PASSWORD=root"
      - "MYSQL_USER=buydating"
      - "MYSQL_PASSWORD=secret"
      - "MYSQL_DATABASE=buydating"
    ports:
      - "33061:3306"
  redis:
    image: redis:3.0
    ports:
      - "63791:6379"
  node:
    image: node:10.15-alpine
    volumes:
      - ./:/var/www
    working_dir: /var/www
    tty: true
  composer:
    image: composer:latest
    volumes:
      - .:/app
    command: 'true'
